### ISSUE TITLE
Reversing#9034

### ISSUE THREAD

**Issue by Charles-QC** [Wafelack/dict#3]
Discord: Reversing#9034

**Comment by Wafelack** [comment]
In "add friend" section it says that it's invalid

**Comment by Charles-QC** [comment]
[ELF]#1337

**Comment by Charles-QC** [comment]
Enft je suis "Hunters"

**Comment by Charles-QC** [comment]
Mouai j'ai encore changer de pseudo Seku#1337 la je change plus tu peux m'add
